language: node_js
node_js:
  - "0.10"
git:
  submodules: false
before_install: npm install -g grunt-cli
before_script: bower install
env:
  global:
    - secure: Ad2KBmwfS2Mr+LxmQs77IMBBtJ6egEIuLO27hBPFK6srAtXDuDS3xmI5tX55p9gQg0gOMd9ZGZ4mjgDvWzY/nK5GNTJcTV2JLPh/jwcikusfPw11FrRCIfs9zNK4beAALSZ4eoxn2UGjXAIO3Ce+Hq/HYnxcH22mc0HiVbK39kI=
    - secure: xSzy2FfniyngrLB0+IiDBlt0FTsdjhkY+9bV+pEmdBmqv5Tgkce9Em4ukTkOBxh3iRKEG+uK4JhilP0yhb5OmRI4U/HhNSV/hK+6JuQ9waW0fPwbjdqfW2TCjndoAEhGB0Ec5AOa5DPoe0/HURjjgwv6O4H38fTl6xv/ajlskV4=
addons:
  sauce_connect: true